# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVM-Article-Project' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVVM-Article-Project
pod 'Alamofire', '~> 5.4'
pod 'Kingfisher', '~> 6.0'
pod 'SwiftLint'
pod 'SwiftyJSON'

  target 'MVVM-Article-ProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MVVM-Article-ProjectUITests' do
    # Pods for testing
  end

end
